web/pay/urls.py
from django.conf.urls import  url
from django.contrib.admin.views.decorators import staff_member_required

from pay.views import *
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^planes/form/$', staff_member_required(PlanesForm), name='pay_planes_form'),
    url(r'^tienda/(?P<compra_id>(\d*))$', buy_my_productos,name='pay_tienda'),
    url(r'^donacion/$', buy_my_donacion,name='pay_donacion'),
    url(r'^ministerial/$', login_required(buy_my_ministerial),name='pay_ministerial'),
    url(r'^premium/$', login_required(buy_my_premium),name='pay_premium'),
    url(r'^entrada/(?P<entrada_id>(\d*))/$', buy_my_entrada,name='pay_entrada'),
    url(r'^return/$', login_required(return_url_premium), name='pay_return_url_premium'),
    url(r'^cancel/$', login_required(cancel_return_premium), name='pay_cancel_return_premium'),
    url(r'^plans/$', HomePayView, name='pay_plans'),
    url(r'^desuscribir/$', cancel_suscription, name='pay_desuscribir'),
    url(r'notifications/$', notifications, name='notifications'),

]

web/tienda/urls.py
from django.conf.urls import url
from django.contrib.admin.views.decorators import staff_member_required

from tienda.ajax import *
from tienda.views import *

urlpatterns = [
    url(r'sin/registro/(?P<producto_id>(\d*))/$', TiendaSinRegistro, name='tienda_sin_registro'),
    url(r'completar/perfil/(?P<producto_id>(\d*))/$', TiendaCompletarPerfil, name='tienda_completar_perfil'),
    url(r'login/(?P<producto_id>(\d*))/$', TiendaLogin, name='tienda_login_producto'),
    url(r'detalle/(?P<compra_id>(\d*))/$', VerDetalle, name='tienda_detalle'),
    url(r'enviar/compra/(?P<compra_id>(\d*))/$', staff_member_required(EnviarCompra), name='tienda_enviar_compra'),
    url(r'envio/(?P<compra_id>(\d*))/$', EnvioProductos, name='tienda_envio'),
    url(r'carrito/menos/(?P<detalle_id>(\d*))/$', MenosDetalle, name='tienda_menos_detalle'),
    url(r'carrito/mas/(?P<detalle_id>(\d*))/$', MasDetalle, name='tienda_mas_detalle'),
    url(r'carrito/eliminar/(?P<detalle_id>(\d*))/$', EliminarDetalle, name='tienda_eliminar_detalle'),
    url(r'carrito/$', Carrito, name='tienda_carrito'),
    url(r'agregar/carrito/(?P<producto_id>(\d*))/$', AgregarCarrito, name='tienda_agregar_carrito'),
    url(r'productos/buscar/$', BuscarProductos, name='tienda_productos_busqueda'),
    url(r'productos/$',TodosProductos,name='tienda_productos'),
    url(r'productos/lista/$',staff_member_required(ListaProductos),name='tienda_productos_lista'),
    url(r'producto/ver/mas/(?P<producto_id>(\d*))/$',ProductoVerMas,name='producto_ver_mas'),
    url(r'producto/nuevo/$',staff_member_required(ProductoNuevo),name='tienda_productos_nuevo'),
    url(r'producto/editar/$',staff_member_required(ProductoEditar),name='tienda_producto_editar'),
    url(r'producto/borrar/$',staff_member_required(producto_borrar),name='producto_borrar'),
    url(r'categoria/lista/$',staff_member_required(ListaCategorias),name='tienda_categoria_lista'),
    url(r'categoria/nueva/$',staff_member_required(CategoriaNueva),name='tienda_categoria_nuevo'),
    url(r'categoria/editar/$',staff_member_required(CategoriaEditar),name='tienda_categoria_editar'),
    url(r'categoria/borrar/$',staff_member_required(borrar_categoria),name='categoria_borrar'),
    url(r'ventas/envio/$', staff_member_required(VentasEnvio), name='tienda_ventas_envio'),
    url(r'ventas/$',staff_member_required(ListaVentas),name='tienda_ventas'),
    url(r'suscribirse/$',Suscribirse,name='suscribirse'),
]

web/tienda/models.py
import os
from datetime import datetime

from cities_light.models import City, Region
from django.contrib.sites.models import Site
from django.db import models

# Create your models here.
from model_utils.managers import InheritanceManager
from s3direct.fields import S3DirectField

from accounts.models import MyUser, _generate_code
from tienda.emails import email_envio


class CategoriaProducto(models.Model):
    nombre = models.CharField(max_length=256)

    def __str__(self):
        return self.nombre

    def get_nombre(self):
        return self.nombre

    def get_tipos(self):
        lista = []
        cant_total=0
        for tipo in TipoProducto.objects.all():
            cant_tipo=len(Producto.objects.filter(tipo=tipo,categoria=self,eliminado=False))
            cant_total+= cant_tipo
            lista.append(cant_tipo)
        lista.append(cant_total)
        return lista

    def set_nombre(self,nombre):
        self.nombre = nombre


class TipoProducto(models.Model):
    nombre = models.CharField(max_length=25)

    def __str__(self):
        return self.nombre

    def get_nombre(self):
        return self.nombre

    def mas_vendidos(self):
        return Producto.objects.filter(tipo=self.id).order_by('cantidad_vendidos')[:3]

    def es_libro_fisico(self):
        return (self.id==4)

class Producto(models.Model):
    nombre = models.CharField(max_length=256)
    descripcion = models.TextField()
    precio = models.FloatField()
    categoria = models.ForeignKey(CategoriaProducto)
    tipo = models.ForeignKey(TipoProducto)
    descuento = models.FloatField(null=True,blank=True)
    archivo = S3DirectField(dest=os.environ.get('AWS_STORAGE_BUCKET_NAME'),null=True,blank=True)
    imagen = S3DirectField(dest=os.environ.get('AWS_STORAGE_BUCKET_NAME'),null=True,blank=True)
    imagen2 = S3DirectField(dest=os.environ.get('AWS_STORAGE_BUCKET_NAME'),null=True,blank=True)
    imagen3= S3DirectField(dest=os.environ.get('AWS_STORAGE_BUCKET_NAME'),null=True,blank=True)
    stock = models.IntegerField(null=True,blank=True)
    eliminado = models.BooleanField(default=False)
    cantidad_vendidos=models.IntegerField(default=0)
    fecha = models.DateField(auto_now_add=True)

    def __str__(self):
        return "%s-%s" %(self.nombre,self.tipo)

    def get_imagen2(self):
        return self.imagen2

    def get_nombre_corto(self):
        if len(self.nombre)>15:
            return self.nombre[:15]+"..."
        else:
            return self.nombre[:15]

    def get_imagen2_url(self):
        if self.imagen2:
            return self.imagen2
        else:
            return "/static/unify-ecommerce/img/blog/31.jpg"

    def get_imagen3_url(self):
        if self.imagen3:
            return self.imagen3
        else:
            return "/static/unify-ecommerce/img/blog/29.jpg"

    def get_imagen_url(self):
        if self.imagen:
            return self.imagen
        else:
            return "/static/unify-ecommerce/img/blog/25.jpg"

    def get_imagen3(self):
        return self.imagen3

    def get_nombre(self):
        return self.nombre

    def get_descripcion(self):
        return self.descripcion

    def get_precio(self):
        return self.precio

    def get_categoria(self):
        return self.categoria

    def get_tipo(self):
        return self.tipo

    def get_archivo(self):
        return self.archivo

    def get_imagen(self):
        return self.imagen

    def get_stock(self):
        return self.stock

    def quitar_stock(self,cantidad):
        self.stock = self.stock-cantidad
        self.cantidad_vendidos+=cantidad
        self.save()

    def hay_stock_s(self):
        if self.tipo.es_libro_fisico and self.stock==0:
            return False
        else:
            return True

    def hay_stock(self,cantidad):
        if self.tipo.es_libro_fisico() and (self.stock-cantidad)<0:
            return False
        else:
            return True

    def subido_este_mes(self):
        now = datetime.now()
        return (now.year==self.fecha.year and now.month==self.fecha.month)

    def set_data(self,producto):
        self.stock = producto.stock
        self.nombre= producto.nombre
        self.descripcion= producto.descripcion
        self.precio = producto.precio
        self.categoria= producto.categoria
        self.imagen = producto.imagen
        self.imagen2 = producto.imagen2
        self.imagen3 = producto.imagen3
        self.descuento = producto.descuento
        self.archivo=producto.archivo

    def eliminar(self):
        self.eliminado=True


    def get_descuento(self):
        return self.descuento

    def get_cantidad_vendidos(self):
        return self.cantidad_vendidos


    def get_precio_descuento(self):
        if self.descuento:
            if self.descuento>0 and self.descuento<100:
                return round(self.precio*(1-(self.descuento/100)),2)
        return self.precio


class EstadoCompra(models.Model):
    nombre = models.CharField(max_length=25)
    objects = InheritanceManager()

    def es_incompleta(self):
        return False

    def es_pagado(self):
        return False

    def es_enviado(self):
        return False

    def enviar(self,compra):
        pass

    def pagar(self,compra):
        pass

    def enviar(self,compra,codigo,url):
        pass

    def __str__(self):
        return self.nombre


class Incompleta(EstadoCompra):
    def es_incompleta(self):
        return True

    def es_pagado(self):
        return False

    def es_enviado(self):
        return False

    def enviar(self,compra):
        pass

    def pagar(self,compra):
        if compra.tiene_libro_fisico():
            compra.set_estado(Pagado.objects.all().first())
            compra.quitar_stock()
        else:
            compra.set_estado(Enviado.objects.all().first())
        compra.save()

    def envio(self,compra,codigo,url):
        pass


class Pagado(EstadoCompra):
    def es_pagado(self):
        return True

    def es_incompleta(self):
        return False

    def es_enviado(self):
        return False

    def enviar(self,compra):
        pass

    def pagar(self,compra):
        pass

    def enviar(self,compra,codigo,url):
        compra.set_codigo(codigo)
        compra.set_url_envio(url)
        compra.set_estado(Enviado.objects.all().first())
        compra.save()


class Enviado(EstadoCompra):
    def es_enviado(self):
        return True

    def es_pagado(self):
        return False

    def es_incompleta(self):
        return False

    def enviar(self,compra):
        pass

    def pagar(self,compra):
        pass

    def enviar(self,compra,codigo,url):
        compra.set_codigo(codigo)
        compra.set_url_envio(url)
        compra.save()


class Compra(models.Model):
    token = models.CharField(max_length=256)
    nombre = models.CharField(max_length=256,null=True,blank=True)
    email = models.EmailField(null=True,blank=True)
    direccion = models.CharField(max_length=256,null=True,blank=True)
    provincia = models.ForeignKey(Region,null=True,blank=True)
    ciudad = models.ForeignKey(City,null=True,blank=True)
    user = models.ForeignKey(MyUser,null=True,blank=True)
    total = models.FloatField(null=True,blank=True)
    estado = models.ForeignKey(EstadoCompra,default=1)
    fecha=models.DateField(auto_now_add=True)
    codigo_seguimiento = models.CharField(max_length=256,null=True,blank=True)
    url_envio = models.URLField(null=True,blank=True)

    def get_user(self):
        return self.user

    def __str__(self):
        return "%i-%s"%(self.id,self.get_nombre())

    def enviar_email_envio(self,request):
        email_envio(request,self)

    def verificar_libros(self):
        for detalle in self.get_detalle():
            if not detalle.get_producto().hay_stock(detalle.get_cantidad()):
                detalle.delete()
                return False
        return True

    def get_url_envio(self):
        return self.url_envio

    def get_codigo(self):
        return self.codigo_seguimiento

    def set_codigo(self,codigo):
        self.codigo_seguimiento = codigo

    def set_url_envio(self,url):
        self.url_envio = url

    def get_nombre(self):
        if self.user:
            return self.user.get_full_name()
        else:
           return self.nombre
    
    def tiene_libro_fisico(self):
        for detalle in self.get_detalle():
            if detalle.get_producto().get_tipo().es_libro_fisico():
                return True
        return False

    def get_email(self):
        if self.user:
            return self.user.get_email()
        else:
            return self.email

    def get_provincia(self):
        if self.user:
            return self.user.get_provincia()
        else:
            return self.provincia

    def get_ciudad(self):
        return self.ciudad

    def get_direccion(self):
        return self.direccion

    def get_estado(self):
        return EstadoCompra.objects.get_subclass(id=self.estado.id)

    def get_detalle(self):
        return DetalleCompra.objects.filter(compra=self)

    def get_total(self):
        if self.get_estado().es_incompleta:
            total= 0
            for detalle in self.get_detalle():
                total = total + detalle.get_parcial()
            return total
        else:
            return self.total

    def set_token(self):
        self.token = str(_generate_code())
        self.token = self.token[2:len(self.token)-1]

    def set_user(self,user):
        self.user = user

    def set_direccion(self,direccion):
        self.direccion = direccion

    def get_token(self):
        return str(self.token)

    def agregar_producto(self,producto,cantidad):
        if DetalleCompra.objects.filter(compra=self,producto=producto):
            detalle = DetalleCompra.objects.get(compra=self,producto=producto)
            detalle.agregar()
        else:
            if producto.get_tipo().es_libro_fisico() and cantidad>0:

web/evento/forms.py
from cities_light.models import City, Region, Country
from django import forms
from evento.models import Evento, Entrada


class FormEvento(forms.ModelForm):
    class Meta:
        model = Evento
        fields = ['nombre', 'descripcion', 'imagen', 'fecha', 'cupo', 'precio', 'categoria', 'direccion', 'ciudad',
                  'tipo_evento', 'provincia']
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control b-r-xl', 'required': True, "maxlength": "256"}),
            'descripcion': forms.Textarea(attrs={'class': 'form-control b-r-xl', 'required': True}),
            'fecha': forms.DateInput(attrs={'class': 'form-control b-r-xl', 'required': True}),
            'cupo': forms.NumberInput(
                attrs={'class': 'form-control b-r-xl presencial', "min": "1", "placeholder": "50"}),
            'precio': forms.NumberInput(attrs={'class': 'form-control b-r-xl', "min": "0", "placeholder": "47.99"}),
            'categoria': forms.Select(attrs={'class': 'form-control b-r-xl', 'required': True}),
            'direccion': forms.TextInput(attrs={'class': 'form-control b-r-xl presencial', "maxlength": "256"}),
            'ciudad': forms.Select(attrs={'class': 'form-control b-r-xl'}),
            'provincia': forms.Select(attrs={'class': 'form-control b-r-xl presencial'}),
            'tipo_evento': forms.Select(attrs={'class': 'form-control b-r-xl', 'required': True}),
        }

    def __init__(self,*args, **kwargs):
        super(FormEvento, self).__init__(*args,**kwargs)
        self.fields["ciudad"].choices = City.objects.none()
        self.fields["provincia"].choices = Region.objects.none()

class FormEventoEdit(forms.ModelForm):
    class Meta:
        model = Evento
        fields = ['nombre', 'descripcion', 'imagen', 'cupo', 'precio', 'direccion',"fecha"]
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control b-r-xl', 'required': True, "maxlength": "256"}),
            'descripcion': forms.Textarea(attrs={'class': 'form-control b-r-xl', 'required': True}),
            'cupo': forms.NumberInput(
                attrs={'class': 'form-control b-r-xl presencial', "min": "1", "placeholder": "50"}),
            'precio': forms.NumberInput(attrs={'class': 'form-control b-r-xl', "min": "0", "placeholder": "47.99"}),
            'direccion': forms.TextInput(attrs={'class': 'form-control b-r-xl presencial', "maxlength": "256"}),
            'fecha': forms.DateInput(attrs={'class': 'form-control b-r-xl', 'required': True}),
        }


class PerfilCompletar(forms.Form):
    pais = forms.ModelChoiceField(queryset=Country.objects.all(),widget=forms.Select(attrs={'class':'form-control b-r-xl',
                                                                                            'required':True}))
    provincia = forms.ModelChoiceField(queryset=Region.objects.none(),widget=forms.Select(attrs={'class':'form-control b-r-xl',
                                                                                              'required':True}))
    email = forms.EmailField(required=False)


class EntradaForm(forms.ModelForm):
    class Meta:
        model=Entrada
        fields=["nombre","email","provincia"]
        widgets={
            "nombre":forms.TextInput(attrs={"class":"form-control b-r-xl","required":True,"placeholder":"Nombre"}),
            "email":forms.EmailInput(attrs={"class":"form-control b-r-xl","required":True,"placeholder":"Email"}),
            "provincia":forms.Select(attrs={"class":"form-control b-r-xl","required":True}),
        }

    def __init__(self,*args,**kwargs):
        super(EntradaForm,self).__init__(*args,**kwargs)
        self.fields["provincia"].choices = Region.objects.none()

class EventoTransmitir(forms.Form):
    url = forms.CharField(widget=forms.TextInput(attrs={"class":"form-control b-r-xl","required":True}))

web/tienda/templates/aux_productos.html
<a href="{% url 'producto_ver_mas' producto_id=producto.id %}">
<div class="thumb-product">
    <img class="thumb-product-img" src="{{producto.get_imagen2_url}}" alt="{{producto.get_nombre}}" width="180" height="180">
    <div class="thumb-product-in">
        <h4><a href="{% url 'producto_ver_mas' producto_id=producto.id %}" style="max-width:150px;overflow:hidden;white-space:nowrap;text-overflow: ellipsis;">{{producto.get_nombre}}</a></h4>
        <span class="thumb-product-type">{{producto.get_tipo}} - {{producto.get_tipo}}</span>
    </div>
    <ul class="list-inline overflow-h">
        {% if producto.get_descuento%}
        <li class="thumb-product-price line-through">${{producto.get_precio}}</li>
        {%endif%}
        <li class="thumb-product-price">${{producto.get_precio_descuento}}</li>
        <li class="thumb-product-purchase"><a href="{% url 'tienda_agregar_carrito' producto_id=producto.id%}?next={%url 'tienda_productos'%}"><i class="fa fa-shopping-cart"></i></a></li>
    </ul>
</div>
</a>

web/tienda/templates/tienda_categoria_editar.html
{%extends 'tienda_categoria_nuevo.html' %}

{%block here%}
Editar Categoria
{%endblock%}

{%block list_here%}
<li>Tienda</li>
<li><a href="{%url 'tienda_productos_lista'%}">Producto</a></li>
<li><a href="{%url 'tienda_categoria_lista' %}">Categorias</a></li>
<li class="active">Editar Categoria</li>
{%endblock%}

{%block form%}.?categoria_id={{categoria.id}}{%endblock%}

{%block btn %}Guardar{%endblock%}

web/tienda/templates/tienda_detalle.html
{% extends 'home_index.html' %}
{% load staticfiles %}

{%block tienda%}
active
{%endblock%}

{%block tienda_in%}
in
{%endblock%}

{%block ventas%}
active
{%endblock%}

{%block ventas_ver%}
active
{%endblock%}

{%block here%}
Ventas
{%endblock%}

{%block list_here%}
<li>Ventas</li>
<li>Todas</li>
<li class="active">Productos</li>
{%endblock%}



{%block contenido%}
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-content">
                    <h1>{{compra.get_nombre}}</h1>
                    <h3>{{compra.get_email}}</h3>
                    <h4>${{compra.get_total}} - {{compra.get_estado}} - {{compra.get_provincia}}</h4>
                    {% if compra.get_codigo %}
                        <h4>Codigo seguimiento <a href="{{compra.get_url_envio}}">{{compra.get_codigo}}</a></h4>
                    {%endif%}
                <div class="table-responsive">
                <table class="table">
                    <thead>
                    <tr>
                        <th>Producto</th>
                        <th>Tipo</th>
                        <th>Categoria</th>
                        <th>Precio</th>
                        <th>Cantidad</th>
                    </tr>
                    </thead>
                    <tbody>
                    {%for detalle in compra.get_detalle%}
                    <tr>
                            <td>{{detalle.get_producto}}</td>
                            <td>{{detalle.get_producto.get_tipo}}</td>
                            <td>{{detalle.get_producto.get_categoria}}</td>
                            <td>{%if detalle.get_precio%}{{detalle.get_precio}}{%else%}{{detalle.get_producto.get_precio}}{%endif%}</td>
                            <td>{{detalle.get_cantidad}}</td>
                    </tr>
                    {%endfor%}
                    </tbody>
                </table>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
{%endblock%}

web/tienda/templates/tienda_perfil_completar.html
{% extends 'home_login.html'%}

{% block title %}Completa tus datos{% endblock %}

{% block titulo %}Completa tus datos{% endblock %}

{%block redes_sociales %}
{%endblock%}

{%block form%}
    <form method="post" action="">
        {% csrf_token %}
        {% include "home_form_errors.html" %}
        {%if user.get_email%}
        <div class="form-group">
            {{form.email}}
        </div>
        {%endif%}
        <div class="form-group">
            {{form.pais}}
        </div>
        <div class="form-group">
            {{form.provincia}}
        </div>
        <div class="form-group">
            {{form.nombre}}
        </div>
        <div class="form-group">
            {{form.direccion}}
        </div>
        <button type="submit" class="login-btn">INGRESAR</button>
    </form>

<script>
    $(document).ready(function(){
        $("#id_pais").on("change",get_provincias);
        get_provincias();

        function get_provincias(){
            let id_pais = $('select[name=pais]').val();
            if(id_pais){
                $("#id_provincia").html("");
                let request = $.ajax({
                    type: "GET",
                    url: "{% url 'get_regions' %}",
                    data:{
                        "id_country" : id_pais
                    },
                });
                request.done(function(response){
                    $("#id_provincia").html(response.regions);
                    $("#id_provincia").trigger("change");
                })
            }else{
                 $("#id_provincia").html("<option value='' selected='selected'>---------</option>");
                 $("#id_provincia").trigger("change");
            }
        };

    });
</script>
{%endblock%}

web/tienda/templates/tienda_productos_nuevo.html
{%extends 'home_index.html' %}

{%block head%}
    {{block.super}}
    {{form.media}}
{%endblock%}

{%block tienda%}
active
{%endblock%}

{%block tienda_in%}
in
{%endblock%}

{%block productos%}
active
{%endblock%}

{%block productos_ver%}
active
{%endblock%}

{%block here%}
Nuevo Producto
{%endblock%}

{%block list_here%}
<li><a href="{%url 'tienda_productos_lista'%}">Productos</a></li>
<li class="active">Nuevo Producto</li>
{%endblock%}

{%block contenido%}
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox-content">
                <form action="{%block action %}.{%endblock%}" method="POST" class="form-horizontal" id="form">
                    {% csrf_token %}
                    {% include 'home_form_errors.html' %}
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Nombre</label>
                        <div class="col-sm-10">
                            {{form.nombre}}
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Descripción</label>
                        <div class="col-sm-10">
                            {{form.descripcion}}
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Categoria</label>
                        <div class="col-sm-10">
                            {{form.categoria}}
                            <span class="help-block m-b-none">
                                <a href="{% url 'tienda_categoria_nuevo' %}">Puedes agregar una haciendo click aqui.</a>
                            </span>
                        </div>
                    </div>
                    <div class="form-group" id="precio">
                        <label class="col-sm-2 control-label">Precio</label>
                        <div class="col-sm-10">
                            {{form.precio}}
                        </div>
                    </div>
                    <div class="form-group" id="descuento">
                        <label class="col-sm-2 control-label">Descuento</label>
                        <div class="col-sm-10">
                            {{form.descuento}}
                        <span class="help-block m-b-none">
                                Descuento en porcentaje(0% a 99%)
                        </span>
                        </div>
                    </div>
                    {%block no_form%}
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Tipo</label>
                        <div class="col-sm-10">
                            {{form.tipo}}
                        </div>
                    </div>
                    {%endblock%}
                    {% block stock%}
                    <div class="form-group" id="stock">
                        <label class="col-sm-2 control-label">Stock</label>
                        <div class="col-sm-10">
                            {{form.stock}}
                        </div>
                    </div>
                    {%endblock%}
                    <div class="form-group" id="archivo">
                        <label class="col-sm-2 control-label" >Archivo</label>
                        <div class="col-sm-10">
                            {{form.archivo}}
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Imagen</label>
                        <div class="col-sm-10">
                            {{form.imagen}}
                            <span class="help-block m-b-none">
                                Tamaño recomendado 370x555
                            </span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Imagen 2</label>
                        <div class="col-sm-10">
                            {{form.imagen2}}
                            <span class="help-block m-b-none">
                                Tamaño recomendado 250X250
                            </span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Imagen 3</label>
                        <div class="col-sm-10">
                            {{form.imagen3}}
                            <span class="help-block m-b-none">
                                Tamaño recomendado 550x560
                            </span>
                        </div>
                    </div>
                    <div class="text-center">
                        <button type="submit"  class="btn btn-success" id="btn">{% block btn %}Nuevo Producto!{%endblock%}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{%endblock%}


{%block javascript_custom%}
<script type="text/javascript">
    $(document).ready(function(){
        ocultarStock();
        $("#id_tipo").on("change",ocultarStock);

        function ocultarStock(){
            if($("#id_tipo").val() && $("#id_tipo").val()!="4"){
                $("#stock").addClass("sr-only");
                $("#archivo").removeClass("sr-only");
            }else{
                $("#stock").removeClass("sr-only");
                $("#archivo").addClass("sr-only");
            }
        }
    });
</script>
{%endblock%}

web/tienda/templates/tienda_sin_registro.html
{% extends 'home_login.html'%}

{% block title %}Completa tus datos{% endblock %}

{% block titulo %}Completa tus datos{% endblock %}

{%block redes_sociales %}
{%endblock%}


{%block form%}
    <form method="post" action=".">
        {% csrf_token %}
        {% include "home_form_errors.html" %}
        <div class="form-group">
            {{form.nombre}}
        </div>
        <div class="form-group">
            {{form.email}}
        </div>
        <div class="form-group">
            <select class="form-control b-r-xl" name="pais" id="id_pais">
                <option value='' selected='selected'>-Selecciona tu Pais-</option>
                {%for c in countrys%}
                    <option value="{{c.id}}">{{c.name}}</option>
                {%endfor%}
            </select>
        </div>
        <div class="form-group">
            {{form.provincia}}
        </div>
        <div class="form-group">
            {{form.ciudad}}
        </div>
        <div class="form-group">
            {{form.direccion}}
        </div>
        <button type="submit" class="login-btn">Agregar al Carrito</button>
    </form>

<script>
    $(document).ready(function(){
        $("#id_pais").on("change",get_provincias);
        get_provincias();

        function get_provincias(){
            let id_pais = $('select[name=pais]').val();
            if(id_pais){
                $("#id_provincia").html("");
                let request = $.ajax({
                    type: "GET",
                    url: "{% url 'get_regions' %}",
                    data:{
                        "id_country" : id_pais
                    },
                });
                request.done(function(response){
                    $("#id_provincia").html(response.regions);
                    $("#id_provincia").trigger("change");
                })
            }else{
                 $("#id_provincia").html("<option value='' selected='selected'>-Selecciona tu Provincia-</option>");
                 $("#id_provincia").trigger("change");
            }
        };


        $("#id_provincia").on("change",get_cities);
        get_cities();

        function get_cities(){
            let id_region = $('select[name=provincia]').val();
            if(id_region){
                $("#id_ciudad").html("");
                let request = $.ajax({
                    type: "GET",
                    url: "{% url 'get_cities' %}",
                    data:{
                        "id_region" : id_region
                    },
                });
                request.done(function(response){
                    $("#id_ciudad").html(response.cities);
                    $("#id_ciudad").trigger("change");
                })
            }else{
                 $("#id_ciudad").html("<option value='' selected='selected'>---------</option>");
                 $("#id_ciudad").trigger("change");
            }
        };





    });
</script>
{%endblock%}